### ISSUE TITLE
Support for V4 auth

### ISSUE THREAD

**Issue by puco** [xogroup/helm-chart-s3-publisher#9]
#### Context

* *node version*: N/A
* *docker version*: 17.07.0-ce-rc4
* *helm-chart-s3-publisher version*: docker latest
* *environment* (node, docker, browser): docker
* *any relevant modules used with* (eslint, mocha, etc.): N/A
* *any other relevant information*: N/A

#### What are you trying to achieve or the steps to reproduce ?

When running the server against a EU AWS region the upload is not working.

#### What result did you expect ?

200 OK

#### What result did you observe ?

500 Internal error

The exception which I saw in console:

```
170901/121330.327, [log,error] message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256., stack: InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
    at Request.extractError (/opt/app/current/node_modules/aws-sdk/lib/services/s3.js:539:35)
    at Request.callListeners (/opt/app/current/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/opt/app/current/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/opt/app/current/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/opt/app/current/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/app/current/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/app/current/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/app/current/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/app/current/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/opt/app/current/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/opt/app/current/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/opt/app/current/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/opt/app/current/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/app/current/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/app/current/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/app/current/node_modules/aws-sdk/lib/request.js:38:9)
```

More info: [https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4](https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4)

**Comment by lamchakchan** [comment]
@puco I will look into this.  

So your `S3` bucket in the EU region?  I'm going to try this setup today and will respond back.

**Comment by lamchakchan** [comment]
Let me know if it doesn't fix it.

**Comment by puco** [comment]
Works without any issues. Thanks
